### ISSUE TITLE
url

### ISSUE THREAD

**Issue by Swatchel** [panthersdude2001/GShareX#2]
url http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe is unreachable now.
Please fix this url in your code

**Comment by panthersdude2001** [comment]
Sorry for the long wait @Swatchel 
In case you have not heard, GShareX is no longer being developed because of a redundancy of ShareX.
TLS 1.2 is now required in Google Photos, and is not available in NDP 4.0. Because of this, GShareX is being archived.
Sorry about that.
Closing as this is a invalid question.
